// PAC scenario names and question sets — CJS mirror of src/core/scenarios.js.
// Used by pac-slack.js (Netlify Function). Keep in sync with SCENARIO_QUESTIONS in scenarios.js.

const SCENARIO_NAMES = [
  "Performance Decline",
  "Attendance Issue",
  "Interpersonal Conflict",
  "Policy Violation",
  "Termination Consideration",
  "Accommodation Request",
  "Harassment / Discrimination",
  "Retaliation Concern",
  "Reduction in Force",
  "Leave of Absence",
];

const SCENARIO_QUESTIONS = {
  "Performance Decline": [
    { q: "Have performance expectations been clearly communicated in writing?", hint: "Verbal expectations alone are harder to defend. Look for emails, job descriptions, goal-setting documents, or meeting notes.", weight: 2, critical: false },
    { q: "Has this issue been documented in prior conversations or reviews?", hint: "A first documented conversation is fine — just make sure it is documented. Verbal-only history creates risk.", weight: 1, critical: false },
    { q: "Has the employee been given a clear opportunity to respond to concerns?", hint: "This means a real conversation, not just an email. The employee should be able to explain context.", weight: 1, critical: false },
    { q: "Is the performance decline consistent and ongoing (not a single incident)?", hint: "A pattern over time is stronger than one bad week. Consider whether something changed.", weight: 1, critical: false },
    { q: "Are there known leave, medical, or accommodation factors at play?", hint: "If yes, or if you're not sure, stop and consult HR before taking any action.", weight: 2, critical: true },
  ],
  "Attendance Issue": [
    { q: "Is there a written attendance policy the employee has acknowledged?", hint: "Without a clear policy, enforcement is difficult to defend. Check your employee handbook.", weight: 2, critical: false },
    { q: "Has the pattern been documented with dates and frequency?", hint: "A log of specific dates and context provided matters enormously if this progresses to discipline.", weight: 1, critical: false },
    { q: "Has the employee been formally notified that attendance is an issue?", hint: "A documented conversation is required before formal discipline.", weight: 1, critical: false },
    { q: "Have you confirmed that no protected leave applies to these absences?", hint: "FMLA, ADA, state sick leave, and other protections can cover absences you might otherwise count.", weight: 2, critical: true },
    { q: "Has the policy been enforced consistently across your team?", hint: "If you have tolerated similar patterns from others, disciplining one person exposes you to disparate treatment claims.", weight: 2, critical: false },
  ],
  "Interpersonal Conflict": [
    { q: "Have you gathered facts from all parties involved, not just the complainant?", hint: "Acting on one person's account without hearing others is a procedural mistake.", weight: 2, critical: false },
    { q: "Have you given each affected employee an opportunity to be heard?", hint: "This protects both the process and the employees.", weight: 1, critical: false },
    { q: "Is the behavior materially affecting work output, team function, or the work environment?", hint: "Personality differences are not automatically an HR matter.", weight: 1, critical: false },
    { q: "Are there prior documented incidents involving these individuals?", hint: "A pattern changes the situation significantly.", weight: 1, critical: false },
    { q: "Is the situation escalating or involving behavior tied to a protected characteristic?", hint: "If the behavior involves race, gender, age, religion, or other protected characteristics, this may be harassment.", weight: 2, critical: true },
  ],
  "Policy Violation": [
    { q: "Is the policy written, accessible, and clearly worded?", hint: "Employees must have had reasonable access to the policy before the violation occurred.", weight: 2, critical: false },
    { q: "Has this policy been applied consistently to others in similar situations?", hint: "Disciplining one person for a violation while ignoring the same behavior from others is a disparate treatment risk.", weight: 2, critical: true },
    { q: "Would the employee reasonably have understood that this behavior violated policy?", hint: "Even with a written policy, enforcement requires the employee could reasonably have known this applied.", weight: 1, critical: false },
    { q: "Is this a first offense, or is there prior disciplinary history?", hint: "Most progressive discipline frameworks require different responses for first vs. repeat violations.", weight: 1, critical: false },
    { q: "Are there mitigating circumstances that warrant consideration before acting?", hint: "Long tenure, clean history, personal circumstances, or policy ambiguity are factors attorneys will ask about.", weight: 1, critical: false },
  ],
  "Termination Consideration": [
    { q: "Is there documented progressive discipline (verbal, written, PIP if applicable)?", hint: "A clean progressive record is your primary defense against wrongful termination claims.", weight: 2, critical: false },
    { q: "Was the employee given a genuine opportunity to improve with clear expectations?", hint: "PIPs and written warnings only protect you if the employee was given a real chance to meet them.", weight: 1, critical: false },
    { q: "Are you following your organization's written termination process?", hint: "Many wrongful termination claims hinge on whether your own process was followed.", weight: 2, critical: false },
    { q: "Is there any legal or protected-leave exposure connected to this employee?", hint: "Recent FMLA leave, ADA accommodation, protected complaint, or pregnancy all create heightened scrutiny.", weight: 2, critical: true },
    { q: "Has HR or legal been consulted if required by your process or the circumstances?", hint: "For terminations with legal exposure flags, employment counsel should be involved before you act.", weight: 2, critical: true },
  ],
  "Accommodation Request": [
    { q: "Has the accommodation request been acknowledged and documented in writing?", hint: "Even a verbal request triggers obligations. The interactive process begins when the need is expressed.", weight: 1, critical: false },
    { q: "Have you initiated the interactive process with the employee?", hint: "The interactive process means a real, documented conversation about what the employee needs. It is legally required.", weight: 2, critical: true },
    { q: "Has HR or legal been informed and involved?", hint: "Accommodation decisions should not be made by a manager alone.", weight: 2, critical: true },
    { q: "Have you obtained the necessary medical documentation (if applicable)?", hint: "You can request documentation confirming the need — but only ask for what is directly relevant.", weight: 1, critical: false },
    { q: "Have you assessed whether accommodation creates undue hardship?", hint: "Undue hardship is a high legal bar. Most accommodations do not meet this threshold.", weight: 1, critical: false },
  ],
  "Harassment / Discrimination": [
    { q: "Has the complaint been documented and acknowledged to the complainant?", hint: "The employee must know their complaint was received and taken seriously.", weight: 1, critical: false },
    { q: "Is HR or legal already involved in this situation?", hint: "Non-negotiable for harassment and discrimination complaints.", weight: 2, critical: true },
    { q: "Has the complainant been informed of their protections against retaliation?", hint: "This is a required communication in most jurisdictions. It should happen at the outset, in writing.", weight: 1, critical: false },
    { q: "Is a neutral investigation underway or formally planned?", hint: "An investigation must be prompt, thorough, and conducted by someone without a conflict of interest.", weight: 2, critical: true },
    { q: "Are the parties currently separated to minimize further harm while the investigation proceeds?", hint: "This may mean schedule adjustments or remote work — but must not punish the complainant.", weight: 1, critical: false },
  ],
  "Retaliation Concern": [
    { q: "Has the employee engaged in protected activity within the past 12 months?", hint: "Protected activity includes: filing an HR complaint, requesting accommodation, taking FMLA, participating in an investigation.", weight: 2, critical: true },
    { q: "Is the adverse action you are considering closely timed to that activity?", hint: "Courts consider anything within a few weeks to a few months as potentially suspicious.", weight: 2, critical: true },
    { q: "Has HR or legal reviewed the proposed action and its timing?", hint: "No adverse action should proceed in this context without independent review.", weight: 2, critical: true },
    { q: "Is there documented, non-retaliatory business rationale that predates the protected activity?", hint: "If the issue existed before the complaint, show documentation that proves it.", weight: 1, critical: false },
    { q: "Has the employee been informed of their anti-retaliation rights?", hint: "Most federal and state laws require this communication.", weight: 1, critical: false },
  ],
  "Reduction in Force": [
    { q: "Is there a documented, legitimate business rationale for the RIF?", hint: "Budget reduction, restructuring, role elimination — the reason must be real and documentable.", weight: 2, critical: false },
    { q: "Were the selection criteria defined and applied consistently before individuals were identified?", hint: "Selection criteria must be established before you run the names.", weight: 2, critical: true },
    { q: "Has legal reviewed the selection pool for adverse impact?", hint: "Run the statistical analysis: what percentage of each protected group is affected?", weight: 2, critical: true },
    { q: "Have WARN Act obligations been assessed (for US employers)?", hint: "50+ employees laid off in 30 days at a single site may trigger 60-day advance notice requirements.", weight: 2, critical: true },
    { q: "Are severance agreements and required disclosures prepared and legally reviewed?", hint: "Agreements offering severance in exchange for a release of claims must meet specific legal requirements.", weight: 1, critical: false },
  ],
  "Leave of Absence": [
    { q: "Have you confirmed whether the employee is eligible for leave under applicable law?", hint: "FMLA requires 12 months of employment and 1,250 hours. State laws often have lower thresholds.", weight: 1, critical: false },
    { q: "Have you identified which type(s) of leave apply to this situation?", hint: "FMLA, ADA, state medical leave, parental leave, military leave — multiple laws can apply simultaneously.", weight: 2, critical: true },
    { q: "Has the required paperwork been provided to the employee within the legally required timeframe?", hint: "FMLA requires a Notice of Eligibility within 5 business days.", weight: 1, critical: false },
    { q: "Are all leave dates, communications, and medical certifications being documented?", hint: "This protects you if the employee later claims they were not approved.", weight: 1, critical: false },
    { q: "Have you confirmed the return-to-work process and whether an accommodation review is needed?", hint: "An employee returning from medical leave may need an ADA accommodation review.", weight: 1, critical: false },
  ],
};

const NEXT_STEPS = {
  "Performance Decline":        { good: ["Schedule a documented performance conversation this week with specific examples.", "Issue a written memo confirming expectations, the gap, and what success looks like. Get a signature.", "Set a structured check-in date 2–4 weeks out and put it on the calendar."], warn: ["Review your documentation for completeness before scheduling any meeting.", "Consult HR before issuing a formal PIP — confirm the process, timeline, and language.", "Assess whether any accommodation or leave factors need to be cleared before proceeding."], risk: ["Stop. Do not schedule any disciplinary meeting until HR has reviewed the full situation.", "Pull together all documentation and present it to HR for a legal risk assessment.", "Do not take any adverse action until cleared."] },
  "Attendance Issue":           { good: ["Issue a documented verbal or written reminder citing the specific policy and dates of concern.", "Provide the employee a written copy of the attendance policy and note the delivery.", "Set a 30-day monitoring window with clear expectations and a follow-up date."], warn: ["Before issuing any discipline, confirm with HR that no protected leave applies.", "Check whether others with similar patterns have been treated the same way.", "Have HR review your proposed disciplinary action before delivery."], risk: ["Pause all disciplinary action immediately. Do not issue any warnings yet.", "Determine whether FMLA, ADA, state leave, or another protected category covers the absences.", "Legal review is required before any adverse action can proceed."] },
  "Interpersonal Conflict":     { good: ["Facilitate a structured mediation conversation with clear ground rules and documented outcomes.", "Issue a written summary of the conversation and expected behavioral changes to both parties.", "Check in with both parties individually within two weeks to assess whether the resolution is holding."], warn: ["Get written statements from all parties before taking any action.", "Determine whether the behavior meets the threshold for a formal investigation.", "Consult HR on whether this should remain a coaching situation or become a formal matter."], risk: ["Treat this as a potential harassment or hostile work environment situation. Do not attempt to resolve it informally.", "Initiate a formal investigation through HR.", "Loop in HR and employment counsel before communicating anything to the parties."] },
  "Policy Violation":           { good: ["Issue appropriate discipline per your progressive discipline framework.", "Document the violation, the evidence, and the disciplinary action taken. Get a signature.", "Confirm in writing that the employee understands the policy and what a repeat offense would mean."], warn: ["Before acting, audit whether this policy has been applied consistently across the team.", "Confirm the policy was communicated and accessible before the violation occurred.", "Have HR review the proposed disciplinary action and documentation before delivery."], risk: ["Do not issue any discipline yet. Inconsistent enforcement creates disparate treatment liability.", "Conduct a consistency audit across your team and document your findings.", "HR and employment counsel must review before any action is taken."] },
  "Termination Consideration":  { good: ["Proceed with termination following your written process. Do not improvise.", "Prepare final pay, separation paperwork, and benefits information per applicable law.", "Have HR present for the conversation. Keep it brief, factual, and document the meeting."], warn: ["Do not schedule the termination meeting until documentation gaps are addressed.", "Have HR assess whether a final written warning or extended PIP is required first.", "Recheck leave and accommodation status — confirm there is no concurrent protected activity."], risk: ["Stop. Do not schedule, communicate, or hint at the termination until legal review is complete.", "Employment counsel must review the full documentation, timeline, and legal exposure before you proceed.", "Any adverse action right now carries significant legal risk. Wait for clearance."] },
  "Accommodation Request":      { good: ["Continue the interactive process. Document every conversation, decision, and outcome.", "Respond to the employee in writing with the accommodation decision and rationale.", "Set a review date to assess whether the accommodation is working."], warn: ["Initiate the interactive process immediately if it has not started. Delay is itself a violation.", "Do not deny or informally dismiss the request without a documented HR and legal review.", "Ensure every communication about the request is in writing and retained."], risk: ["Do not take any adverse action while the accommodation request is pending.", "Escalate to HR and employment counsel today. The interactive process must begin immediately.", "Failure to engage the interactive process is an independent legal violation."] },
  "Harassment / Discrimination": { good: ["Ensure the investigation is conducted by a neutral party with no stake in the outcome.", "Document all investigation steps, witness interviews, and findings in a formal written report.", "Communicate the outcome to both the complainant and respondent as required by your policy."], warn: ["Separate the parties immediately if they are in direct contact.", "If HR is not already involved, escalate now. Today.", "Confirm in writing to the complainant that retaliation is prohibited."], risk: ["This requires immediate escalation to HR and employment counsel. No exceptions.", "Do not attempt to resolve this informally or conduct the investigation yourself.", "Preserve all related documents, emails, messages, and records. Do not delete anything."] },
  "Retaliation Concern":        { good: ["Document the business rationale for the adverse action independently of any prior protected activity.", "Brief HR on the full timeline — when the protected activity occurred and when the performance issue arose.", "Confirm the employee has received written notice of their anti-retaliation rights."], warn: ["Have employment counsel review the timing and proposed rationale before taking any action.", "Document the non-retaliatory reason in detail, with evidence that predates the protected activity.", "Do not communicate the adverse action until legal review is complete."], risk: ["Stop all adverse action immediately. Do not proceed with any next steps.", "This situation requires employment counsel review before anything else happens.", "Retaliation claims are among the most expensive HR legal exposures."] },
  "Reduction in Force":         { good: ["Proceed with separation meetings per your established RIF protocol and script.", "Ensure all severance agreements comply with applicable law, including OWBPA for employees over 40.", "Provide all required notices, benefits continuation information, and outplacement resources."], warn: ["Complete the adverse impact analysis before finalizing the selection list.", "Confirm WARN Act applicability with employment counsel before announcing dates.", "Ensure every selection decision has a documented, non-discriminatory business rationale."], risk: ["Do not proceed with any separations until employment counsel has signed off.", "The adverse impact analysis and legal review are not optional.", "WARN Act violations, adverse impact claims, and OWBPA defects all carry significant financial exposure."] },
  "Leave of Absence":           { good: ["Provide all required leave paperwork within the legally required timeframe.", "Communicate clearly in writing about return-to-work expectations and the extension process.", "Document all leave-related conversations, approvals, and certifications."], warn: ["Identify the applicable leave type before taking any action.", "Do not count leave-protected absences in any attendance discipline or performance review.", "Consult HR on whether state leave laws provide protections beyond the federal minimum."], risk: ["Stop. Taking any action while leave protections are unconfirmed is high-risk.", "Escalate to HR today to identify all applicable leave laws and employer obligations.", "Legal review is required before any action — including denial of leave or attendance discipline."] },
};

const SCENARIO_META = {
  "Performance Decline": {
    emoji: '📋',
    riskTier: 'moderate',
    description: 'A team member is not meeting expected standards of work output, quality, or behavior. Very manageable when handled with clear documentation and consistent communication.',
    examples: [
      'An employee who consistently missed quarterly targets despite coaching conversations over three months.',
      'A team member whose work quality dropped since returning from a leave of absence.',
      'Someone who used to be a strong performer but has been disengaged and error-prone for six weeks.',
      'An employee who repeatedly submits reports late after multiple reminders.',
      'A customer-facing employee receiving escalating complaints about attitude or responsiveness.',
      'A team member who stops contributing in meetings and misses collaborative deadlines.',
      'Someone who was coached verbally twice and is now making the same errors again.',
    ],
    docGuidance: [
      'Send a follow-up email after every coaching conversation summarizing what was discussed and what is expected.',
      'Use a simple log: date, what you observed, what you said, how the employee responded.',
      'Save any examples of substandard work — reports, emails, error logs — as attachments.',
      'Document goals in writing before any review period begins so expectations are clear.',
      'Note any explanation the employee gave and whether it was substantiated.',
    ],
  },
  "Attendance Issue": {
    emoji: '🕐',
    riskTier: 'moderate',
    description: 'An employee has patterns of tardiness, unexcused absences, or leave usage that exceeds policy limits. Requires careful handling to avoid inadvertently penalizing protected leave.',
    examples: [
      'An employee with six unexcused absences in 90 days who has been verbally reminded of the policy twice.',
      'A team member who is frequently late on Mondays and Fridays without explanation.',
      'Someone whose absences cluster around protected leave and may overlap with an FMLA-qualifying condition.',
      'An employee who exhausted their PTO and continues taking unplanned days off.',
      'A team member whose attendance has declined noticeably since a change in shift or manager.',
    ],
    docGuidance: [
      'Log every absence with date, reason given (or lack of one), and whether it was excused.',
      'Confirm the employee has received and acknowledged the attendance policy in writing.',
      'Before issuing any discipline, check with HR whether any absences qualify as protected leave.',
      'Document every attendance conversation, including verbal reminders.',
      'Track patterns over time — sporadic occurrences look different from a clear ongoing issue.',
    ],
  },
  "Interpersonal Conflict": {
    emoji: '🤝',
    riskTier: 'moderate',
    description: 'Two or more employees have a working relationship that is creating tension, affecting team performance, or producing complaints. May be a coaching situation or may require formal investigation.',
    examples: [
      'Two team members who had a heated argument in a team meeting and are no longer speaking.',
      'An employee who has made three formal complaints about the same colleague in 60 days.',
      'A situation where one employee\'s behavior is described by others as "creating a hostile environment."',
      'A manager-subordinate conflict where the subordinate alleges favoritism or unfair treatment.',
      'An ongoing feud between two high performers that is affecting team morale and output.',
    ],
    docGuidance: [
      'Get written statements from each party separately before drawing any conclusions.',
      'Document the timeline: when complaints were made, what was said, what you observed directly.',
      'Note whether the conflict has affected work product, deadlines, or other team members.',
      'Keep all communications about the situation confidential and on a need-to-know basis.',
      'Record any steps you took to separate the parties or address the issue informally.',
    ],
  },
  "Policy Violation": {
    emoji: '⚠️',
    riskTier: 'moderate',
    description: 'An employee has violated a written workplace policy. Discipline is only defensible if the policy was communicated, applied consistently, and the response is proportionate.',
    examples: [
      'An employee who accessed a colleague\'s computer files without authorization.',
      'A team member who violated the social media policy by posting confidential company information.',
      'Someone who falsified a timesheet or expense report.',
      'An employee who violated the workplace safety policy in a way that created a recordable incident.',
      'A team member who violated the conflict-of-interest policy by working for a competitor on the side.',
    ],
    docGuidance: [
      'Gather evidence of the violation before confronting the employee.',
      'Confirm the policy was in effect, clearly written, and communicated to this employee.',
      'Document how similar violations have been handled for other employees to establish consistency.',
      'Get HR sign-off before delivering discipline — disproportionate responses create liability.',
      'Have the employee sign acknowledgment of the policy and the disciplinary action.',
    ],
  },
  "Termination Consideration": {
    emoji: '🚪',
    riskTier: 'high',
    description: 'You are considering ending an employee\'s employment. This is the highest-risk action a manager can take and requires thorough documentation, HR involvement, and often legal review.',
    examples: [
      'An employee who completed a PIP and still did not meet the stated improvement benchmarks.',
      'A team member terminated for cause after a serious policy violation.',
      'A position being eliminated as part of a departmental restructure.',
      'An employee who has been on a final written warning and committed another infraction.',
      'A probationary employee who is not meeting expectations within their first 90 days.',
    ],
    docGuidance: [
      'Compile the complete performance and discipline history before any termination meeting.',
      'Confirm the termination is not happening within 90 days of any protected activity (complaint, leave, accommodation request).',
      'Have HR review the full documentation and approve the termination before proceeding.',
      'Prepare final pay, benefits continuation notices, and separation paperwork before the meeting.',
      'Document the termination meeting itself: who was present, what was said, how the employee responded.',
    ],
  },
  "Accommodation Request": {
    emoji: '♿',
    riskTier: 'high',
    description: 'An employee has requested a workplace accommodation, typically related to a disability or medical condition. The ADA interactive process is legally required and must be documented carefully.',
    examples: [
      'An employee with a new diagnosis who has requested a modified schedule or remote work arrangement.',
      'A team member returning from medical leave who can\'t perform all prior duties without modification.',
      'An employee whose doctor has placed them on permanent lifting restrictions.',
      'Someone requesting a quiet workspace due to a documented sensory processing condition.',
      'An employee who has not formally used the word "accommodation" but has described a medical limitation affecting their work.',
    ],
    docGuidance: [
      'As soon as an accommodation is requested or implied, notify HR — delay is itself a legal violation.',
      'Document every step of the interactive process: requests, meetings, decisions, counterproposals.',
      'Do not deny a request without HR and legal review — even informal denials carry risk.',
      'Keep medical information strictly confidential and separate from the personnel file.',
      'Set a review date to assess whether the accommodation is working for both parties.',
    ],
  },
  "Harassment / Discrimination": {
    emoji: '🔴',
    riskTier: 'high',
    description: 'An employee has made a complaint or you have observed behavior that may constitute harassment, discrimination, or a hostile work environment. Requires immediate escalation.',
    examples: [
      'An employee who reported that a colleague made repeated comments about their religion.',
      'A team member who alleged that their manager treated them differently because of their age.',
      'A complaint that a coworker has been making unwanted physical contact.',
      'An employee who reported being excluded from meetings and opportunities after disclosing a pregnancy.',
      'A situation where team members are sharing offensive content in a group chat.',
    ],
    docGuidance: [
      'Do not investigate on your own — escalate to HR immediately.',
      'Preserve all relevant communications: emails, Slack messages, texts, meeting notes.',
      'Do not discuss the complaint with others beyond what HR instructs.',
      'Document the date, time, and content of every report you receive.',
      'Issue a written anti-retaliation reminder to both the complainant and the respondent.',
    ],
  },
  "Retaliation Concern": {
    emoji: '🔄',
    riskTier: 'high',
    description: 'An employee has engaged in protected activity (filed a complaint, requested leave or accommodation, reported a safety issue) and you are now considering adverse action against them.',
    examples: [
      'An employee who filed an HR complaint and whose performance review is now due.',
      'A team member who reported a safety violation and is now being considered for a PIP.',
      'Someone who requested FMLA leave and was subsequently reassigned to a less desirable role.',
      'An employee who raised a discrimination concern and is now being managed out.',
      'A situation where adverse action is being taken within 90 days of any protected activity.',
    ],
    docGuidance: [
      'Document the business rationale for any adverse action in writing before taking it.',
      'Establish that the reason for the action predates or is independent of the protected activity.',
      'Have employment counsel review the timing and documentation before proceeding.',
      'Do not proceed with any adverse action until HR and legal have reviewed the full timeline.',
      'Keep a written record of every decision made and who approved it.',
    ],
  },
  "Reduction in Force": {
    emoji: '📉',
    riskTier: 'high',
    description: 'You are eliminating positions as part of a layoff, restructure, or budget reduction. RIF decisions carry significant legal exposure and must be based on documented, non-discriminatory criteria.',
    examples: [
      'A department being consolidated from four roles to two due to a budget cut.',
      'A function being outsourced, eliminating all internal positions in that area.',
      'A site closure that requires terminating all employees at that location.',
      'A restructure where certain job titles are being eliminated across the organization.',
      'A performance-neutral RIF where selection is based on skills, seniority, or role criticality.',
    ],
    docGuidance: [
      'Document the business justification for the RIF before selecting any individuals.',
      'Apply selection criteria consistently and in writing before reviewing specific employees.',
      'Run an adverse impact analysis on the selection list before finalizing it.',
      'Confirm WARN Act notice obligations with employment counsel before setting any dates.',
      'Prepare individualized severance agreements compliant with applicable law, including OWBPA for employees 40+.',
    ],
  },
  "Leave of Absence": {
    emoji: '📅',
    riskTier: 'moderate',
    description: 'An employee has requested or is on a leave of absence. Leave management requires identifying the correct leave type and following a specific process — missteps create independent legal exposure.',
    examples: [
      'An employee who has been out for two weeks and has not yet submitted medical certification.',
      'A team member requesting an extended leave beyond what FMLA covers.',
      'An employee who took intermittent leave and whose absences are now affecting the team.',
      'Someone who returned from leave and is asking to be restored to a different position.',
      'An employee whose leave has expired but who is not yet medically cleared to return.',
    ],
    docGuidance: [
      'Identify the leave type (FMLA, ADA, state law, company policy) before taking any action.',
      'Send written notice of leave designation and employee rights within the required timeframe.',
      'Document all communications about the leave in writing.',
      'Do not count leave-protected absences in attendance records or performance reviews.',
      'Before the employee returns, confirm whether an accommodation review is needed.',
    ],
  },
};

module.exports = { SCENARIO_NAMES, SCENARIO_QUESTIONS, NEXT_STEPS, SCENARIO_META };
