// AUTO-GENERATED by scripts/build-cjs-bridge.js — do not edit directly.
// Source of truth: src/core/. Re-run `npm run build:cjs` after any changes there.

'use strict';

const ANSWERS = {
  "YES": "yes",
  "NO": "no",
  "UNKNOWN": "unknown"
};

const LEVELS = {
  "LOW": "good",
  "ELEVATED": "warn",
  "HIGH": "risk"
};

const RISK_THRESHOLDS = {
  "LOW": 0.15,
  "ELEVATED": 0.45
};

const UNKNOWN_WEIGHT_MULTIPLIER = 0.75;

function computeScore(questions, answers) {
  let weightedNo = 0;
  let totalWeight = 0;
  let hasCriticalFlag = false;
  let countUnknown = 0;
  let countYes = 0;
  let countNo = 0;

  questions.forEach(function(item, i) {
    const answer = answers[i];
    totalWeight += item.weight;

    if (answer === ANSWERS.YES) {
      countYes++;
    } else if (answer === ANSWERS.NO) {
      countNo++;
      weightedNo += item.weight;
      if (item.critical) hasCriticalFlag = true;
    } else if (answer === ANSWERS.UNKNOWN) {
      countUnknown++;
      weightedNo += item.weight * UNKNOWN_WEIGHT_MULTIPLIER;
      if (item.critical) hasCriticalFlag = true;
    }
  });

  const ratio = totalWeight > 0 ? weightedNo / totalWeight : 0;

  const level = hasCriticalFlag
    ? LEVELS.HIGH
    : ratio <= RISK_THRESHOLDS.LOW
    ? LEVELS.LOW
    : ratio <= RISK_THRESHOLDS.ELEVATED
    ? LEVELS.ELEVATED
    : LEVELS.HIGH;

  return { level, hasCriticalFlag, ratio, countYes, countNo, countUnknown, totalWeight, weightedNo };
}

function isComplete(answers, questionCount) {
  return answers.filter(function(a) { return a !== null && a !== undefined; }).length === questionCount;
}

function computeLiveLevel(questions, answers) {
  const answered = answers.filter(function(a) { return a !== null && a !== undefined; });
  if (answered.length === 0) return 'neutral';
  return computeScore(questions, answers).level;
}

module.exports = { ANSWERS, LEVELS, RISK_THRESHOLDS, UNKNOWN_WEIGHT_MULTIPLIER, computeScore, isComplete, computeLiveLevel };
